### ISSUE TITLE
Rogue Ability "Vanish"

### ISSUE THREAD

**Issue by Tixlenra** [Blumfield/Issue#1]
**Description**: Rogue Ability "Vanish"

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)

When using the spell "Vanish" and exiting Stealth, you should not keep the 'Improved Stealth' buff which you gain from the act of Vanishing.

**Expected behaviour**: Tell us what should happen instead

'Improved Stealth' should be removed when Stealth is removed.

**Steps to reproduce the problem**:

1. Learn Vanish
2. Vanish
3. Exit stealth

**Include proofs for this behaviour**

https://www.youtube.com/watch?v=uWjLVlZix2A&feature=youtu.be

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Can't find the ID's on my database...

**Comment by Blumfield** [comment]
Fixed
